object frmLancamentoDeCaixa: TfrmLancamentoDeCaixa
  Left = 0
  Top = 0
  BorderStyle = bsNone
  ClientHeight = 395
  ClientWidth = 884
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -15
  Font.Name = 'Segoe UI'
  Font.Style = []
  Position = poScreenCenter
  PixelsPerInch = 120
  TextHeight = 20
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 884
    Height = 395
    Margins.Left = 4
    Margins.Top = 4
    Margins.Right = 4
    Margins.Bottom = 4
    Align = alClient
    BevelOuter = bvNone
    Color = 8805178
    Padding.Left = 6
    Padding.Top = 6
    Padding.Right = 6
    Padding.Bottom = 6
    ParentBackground = False
    TabOrder = 0
    object Panel8: TPanel
      Left = 6
      Top = 6
      Width = 872
      Height = 35
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Align = alTop
      Alignment = taLeftJustify
      BevelOuter = bvNone
      BiDiMode = bdLeftToRight
      Caption = '   Cadastro de Lan'#231'amentos'
      Color = 13275746
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 15649712
      Font.Height = -21
      Font.Name = 'Segoe UI'
      Font.Style = [fsBold]
      Padding.Left = 6
      Padding.Top = 6
      Padding.Right = 6
      Padding.Bottom = 6
      ParentBiDiMode = False
      ParentBackground = False
      ParentFont = False
      TabOrder = 0
      object Pnl_sair: TPanel
        Left = 756
        Top = 6
        Width = 110
        Height = 23
        Cursor = crHandPoint
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        Align = alRight
        BevelOuter = bvNone
        Color = 13274977
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -15
        Font.Name = 'Segoe UI'
        Font.Style = []
        ParentBackground = False
        ParentFont = False
        TabOrder = 0
        object Shape19: TShape
          Left = 0
          Top = 0
          Width = 110
          Height = 23
          Margins.Left = 4
          Margins.Top = 4
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alClient
          Brush.Color = 8739130
          Shape = stRoundRect
        end
        object SpeedButton6: TSpeedButton
          Left = 0
          Top = 0
          Width = 110
          Height = 23
          Cursor = crHandPoint
          Margins.Left = 4
          Margins.Top = 4
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alClient
          Caption = 'Fechar'
          Flat = True
          Font.Charset = DEFAULT_CHARSET
          Font.Color = 15649712
          Font.Height = -16
          Font.Name = 'Segoe UI'
          Font.Style = []
          Font.Quality = fqClearTypeNatural
          ParentFont = False
          OnClick = SpeedButton6Click
        end
      end
    end
    object Panel2: TPanel
      Left = 6
      Top = 41
      Width = 872
      Height = 348
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Align = alClient
      BevelOuter = bvNone
      Color = 15649712
      Padding.Left = 6
      Padding.Top = 6
      Padding.Right = 6
      Padding.Bottom = 6
      ParentBackground = False
      TabOrder = 1
      object PgcUsuario: TPageControl
        Left = 6
        Top = 6
        Width = 860
        Height = 296
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        ActivePage = TabOperacao
        Align = alClient
        TabOrder = 0
        object TabOperacao: TTabSheet
          Margins.Left = 4
          Margins.Top = 4
          Margins.Right = 4
          Margins.Bottom = 4
          Caption = 'Operacao'
          object Panel4: TPanel
            Left = 0
            Top = 0
            Width = 852
            Height = 261
            Margins.Left = 4
            Margins.Top = 4
            Margins.Right = 4
            Margins.Bottom = 4
            Align = alClient
            BevelOuter = bvNone
            Color = 13274977
            Padding.Left = 6
            Padding.Top = 6
            Padding.Right = 6
            Padding.Bottom = 6
            ParentBackground = False
            TabOrder = 0
            object pnl_dados_user: TPanel
              Left = 6
              Top = 6
              Width = 840
              Height = 249
              Margins.Left = 4
              Margins.Top = 4
              Margins.Right = 4
              Margins.Bottom = 4
              Align = alClient
              BevelOuter = bvNone
              Color = 15649712
              Padding.Left = 6
              Padding.Top = 6
              Padding.Right = 6
              Padding.Bottom = 6
              ParentBackground = False
              TabOrder = 0
              object Panel15: TPanel
                Left = 503
                Top = 16
                Width = 73
                Height = 50
                Margins.Left = 4
                Margins.Top = 4
                Margins.Right = 4
                Margins.Bottom = 4
                Align = alCustom
                BevelOuter = bvNone
                Padding.Right = 6
                TabOrder = 0
                object Shape34: TShape
                  Left = 0
                  Top = 0
                  Width = 67
                  Height = 50
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  Align = alClient
                  Brush.Color = 13275746
                  Shape = stRoundRect
                  ExplicitWidth = 68
                end
                object edtID: TDBLabeledEdit
                  Left = 8
                  Top = 24
                  Width = 52
                  Height = 22
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  BiDiMode = bdLeftToRight
                  BorderStyle = bsNone
                  CharCase = ecUpperCase
                  Color = 13275746
                  DataField = 'ID'
                  DataSource = DS_Lancamento_Caixa
                  Enabled = False
                  Font.Charset = DEFAULT_CHARSET
                  Font.Color = 16512241
                  Font.Height = -15
                  Font.Name = 'Segoe UI'
                  Font.Style = [fsBold]
                  ParentBiDiMode = False
                  ParentFont = False
                  TabOrder = 0
                  EditLabel.Width = 15
                  EditLabel.Height = 20
                  EditLabel.Margins.Left = 8
                  EditLabel.Margins.Top = 8
                  EditLabel.Margins.Right = 8
                  EditLabel.Margins.Bottom = 8
                  EditLabel.BiDiMode = bdLeftToRight
                  EditLabel.ParentBiDiMode = False
                  EditLabel.Layout = tlCenter
                end
              end
              object Panel5: TPanel
                Left = 578
                Top = 16
                Width = 245
                Height = 50
                Margins.Left = 4
                Margins.Top = 4
                Margins.Right = 4
                Margins.Bottom = 4
                Align = alCustom
                BevelOuter = bvNone
                Padding.Right = 6
                TabOrder = 1
                object Shape1: TShape
                  Left = 0
                  Top = 0
                  Width = 239
                  Height = 50
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  Align = alClient
                  Brush.Color = 13275746
                  Shape = stRoundRect
                end
                object edtUsuario: TDBLabeledEdit
                  Tag = 1
                  Left = 8
                  Top = 26
                  Width = 220
                  Height = 23
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  BorderStyle = bsNone
                  CharCase = ecUpperCase
                  Color = 13275746
                  DataField = 'DATALANCAMENTO'
                  DataSource = DS_Lancamento_Caixa
                  Enabled = False
                  Font.Charset = DEFAULT_CHARSET
                  Font.Color = 16512241
                  Font.Height = -15
                  Font.Name = 'Segoe UI'
                  Font.Style = [fsBold]
                  ParentFont = False
                  TabOrder = 0
                  EditLabel.Width = 167
                  EditLabel.Height = 25
                  EditLabel.Margins.Left = 8
                  EditLabel.Margins.Top = 8
                  EditLabel.Margins.Right = 8
                  EditLabel.Margins.Bottom = 8
                  EditLabel.Caption = 'Data do Movimento'
                  EditLabel.Color = clWhite
                  EditLabel.Font.Charset = DEFAULT_CHARSET
                  EditLabel.Font.Color = 15649712
                  EditLabel.Font.Height = -19
                  EditLabel.Font.Name = 'Segoe UI'
                  EditLabel.Font.Style = []
                  EditLabel.ParentColor = False
                  EditLabel.ParentFont = False
                  EditLabel.Layout = tlCenter
                end
              end
              object Panel6: TPanel
                Left = 18
                Top = 16
                Width = 293
                Height = 50
                Margins.Left = 4
                Margins.Top = 4
                Margins.Right = 4
                Margins.Bottom = 4
                Align = alCustom
                BevelOuter = bvNone
                Padding.Right = 6
                TabOrder = 2
                object Shape2: TShape
                  Left = 0
                  Top = 0
                  Width = 287
                  Height = 50
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  Align = alClient
                  Brush.Color = 13275746
                  Shape = stRoundRect
                  ExplicitWidth = 288
                end
                object edtSenha: TDBLabeledEdit
                  Tag = 1
                  Left = 6
                  Top = 26
                  Width = 275
                  Height = 18
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  BiDiMode = bdLeftToRight
                  BorderStyle = bsNone
                  CharCase = ecUpperCase
                  Color = 13275746
                  DataField = 'VALORLANCAMENTO'
                  DataSource = DS_Lancamento_Caixa
                  Font.Charset = DEFAULT_CHARSET
                  Font.Color = 16512241
                  Font.Height = -15
                  Font.Name = 'Segoe UI'
                  Font.Style = [fsBold]
                  ParentBiDiMode = False
                  ParentFont = False
                  TabOrder = 0
                  EditLabel.Width = 47
                  EditLabel.Height = 25
                  EditLabel.Margins.Left = 8
                  EditLabel.Margins.Top = 8
                  EditLabel.Margins.Right = 8
                  EditLabel.Margins.Bottom = 8
                  EditLabel.BiDiMode = bdLeftToRight
                  EditLabel.Caption = 'Valor'
                  EditLabel.Color = clWhite
                  EditLabel.Font.Charset = DEFAULT_CHARSET
                  EditLabel.Font.Color = 15649712
                  EditLabel.Font.Height = -19
                  EditLabel.Font.Name = 'Segoe UI'
                  EditLabel.Font.Style = [fsBold]
                  EditLabel.ParentBiDiMode = False
                  EditLabel.ParentColor = False
                  EditLabel.ParentFont = False
                  EditLabel.Layout = tlCenter
                end
              end
              object Panel7: TPanel
                Left = 18
                Top = 78
                Width = 293
                Height = 153
                Margins.Left = 4
                Margins.Top = 4
                Margins.Right = 4
                Margins.Bottom = 4
                Align = alCustom
                BevelOuter = bvNone
                Padding.Right = 6
                TabOrder = 3
                object Shape3: TShape
                  Left = 0
                  Top = 0
                  Width = 287
                  Height = 153
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  Align = alClient
                  Brush.Color = 13275746
                  Shape = stRoundRect
                  ExplicitWidth = 288
                  ExplicitHeight = 154
                end
                object DBLabeledEdit1: TDBLabeledEdit
                  Tag = 1
                  Left = 10
                  Top = 40
                  Width = 261
                  Height = 101
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  BiDiMode = bdLeftToRight
                  BorderStyle = bsNone
                  CharCase = ecUpperCase
                  Color = 13275746
                  DataField = 'OBSERVACAO'
                  DataSource = DS_Lancamento_Caixa
                  Font.Charset = DEFAULT_CHARSET
                  Font.Color = 16512241
                  Font.Height = -15
                  Font.Name = 'Segoe UI'
                  Font.Style = [fsBold]
                  ParentBiDiMode = False
                  ParentFont = False
                  TabOrder = 0
                  EditLabel.Width = 104
                  EditLabel.Height = 25
                  EditLabel.Margins.Left = 8
                  EditLabel.Margins.Top = 8
                  EditLabel.Margins.Right = 8
                  EditLabel.Margins.Bottom = 8
                  EditLabel.BiDiMode = bdLeftToRight
                  EditLabel.Caption = 'Observa'#231#227'o'
                  EditLabel.Color = clWhite
                  EditLabel.Font.Charset = DEFAULT_CHARSET
                  EditLabel.Font.Color = 15649712
                  EditLabel.Font.Height = -19
                  EditLabel.Font.Name = 'Segoe UI'
                  EditLabel.Font.Style = [fsBold]
                  EditLabel.ParentBiDiMode = False
                  EditLabel.ParentColor = False
                  EditLabel.ParentFont = False
                  EditLabel.Layout = tlCenter
                end
              end
              object Panel9: TPanel
                Left = 319
                Top = 16
                Width = 182
                Height = 215
                Margins.Left = 4
                Margins.Top = 4
                Margins.Right = 4
                Margins.Bottom = 4
                Align = alCustom
                BevelOuter = bvNone
                Padding.Right = 6
                TabOrder = 4
                object Shape4: TShape
                  Left = 0
                  Top = 0
                  Width = 176
                  Height = 215
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  Align = alClient
                  Brush.Color = 13275746
                  Shape = stRoundRect
                end
                object gpTipo: TRadioGroup
                  Left = 13
                  Top = 13
                  Width = 152
                  Height = 181
                  Margins.Left = 6
                  Margins.Top = 6
                  Margins.Right = 6
                  Margins.Bottom = 6
                  Caption = 'Tipo do Lan'#231'amento'
                  Font.Charset = DEFAULT_CHARSET
                  Font.Color = clWindowText
                  Font.Height = -15
                  Font.Name = 'Segoe UI'
                  Font.Style = [fsBold]
                  Items.Strings = (
                    ' -  Saida'
                    ' - Entrada')
                  ParentFont = False
                  TabOrder = 0
                end
              end
              object Panel10: TPanel
                Left = 503
                Top = 74
                Width = 318
                Height = 50
                Margins.Left = 4
                Margins.Top = 4
                Margins.Right = 4
                Margins.Bottom = 4
                Align = alCustom
                BevelOuter = bvNone
                Padding.Right = 6
                TabOrder = 5
                object Shape5: TShape
                  Left = 0
                  Top = 0
                  Width = 312
                  Height = 50
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  Align = alClient
                  Brush.Color = 13275746
                  Shape = stRoundRect
                  ExplicitWidth = 313
                end
                object edtTipo: TDBLabeledEdit
                  Tag = 1
                  Left = 16
                  Top = 28
                  Width = 275
                  Height = 16
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  BiDiMode = bdLeftToRight
                  BorderStyle = bsNone
                  CharCase = ecUpperCase
                  Color = 13275746
                  DataField = 'TIPO'
                  DataSource = DS_Lancamento_Caixa
                  Enabled = False
                  Font.Charset = DEFAULT_CHARSET
                  Font.Color = 16512241
                  Font.Height = -15
                  Font.Name = 'Segoe UI'
                  Font.Style = []
                  ParentBiDiMode = False
                  ParentFont = False
                  TabOrder = 0
                  EditLabel.Width = 37
                  EditLabel.Height = 25
                  EditLabel.Margins.Left = 8
                  EditLabel.Margins.Top = 8
                  EditLabel.Margins.Right = 8
                  EditLabel.Margins.Bottom = 8
                  EditLabel.BiDiMode = bdLeftToRight
                  EditLabel.Caption = 'Tipo'
                  EditLabel.Color = clWhite
                  EditLabel.Font.Charset = DEFAULT_CHARSET
                  EditLabel.Font.Color = 15649712
                  EditLabel.Font.Height = -19
                  EditLabel.Font.Name = 'Segoe UI'
                  EditLabel.Font.Style = []
                  EditLabel.ParentBiDiMode = False
                  EditLabel.ParentColor = False
                  EditLabel.ParentFont = False
                  EditLabel.Layout = tlCenter
                end
              end
            end
          end
        end
        object TabPesquisa: TTabSheet
          Margins.Left = 4
          Margins.Top = 4
          Margins.Right = 4
          Margins.Bottom = 4
          Caption = 'Pesquisa'
          ImageIndex = 1
          object Panel3: TPanel
            Left = 0
            Top = 0
            Width = 852
            Height = 261
            Margins.Left = 4
            Margins.Top = 4
            Margins.Right = 4
            Margins.Bottom = 4
            Align = alClient
            Color = 14079702
            Padding.Left = 5
            Padding.Top = 5
            Padding.Right = 5
            Padding.Bottom = 5
            ParentBackground = False
            TabOrder = 0
            object DBGrid1: TDBGrid
              Left = 6
              Top = 34
              Width = 840
              Height = 221
              Hint = 'Clique duas vezes para selecionar'
              Margins.Left = 4
              Margins.Top = 4
              Margins.Right = 4
              Margins.Bottom = 4
              Align = alClient
              DataSource = DS_Lancamento_Caixa
              ParentShowHint = False
              ReadOnly = True
              ShowHint = True
              TabOrder = 0
              TitleFont.Charset = DEFAULT_CHARSET
              TitleFont.Color = clWindowText
              TitleFont.Height = -15
              TitleFont.Name = 'Segoe UI'
              TitleFont.Style = []
              Columns = <
                item
                  Expanded = False
                  FieldName = 'ID'
                  Title.Caption = 'Id'
                  Width = 80
                  Visible = True
                end
                item
                  Expanded = False
                  FieldName = 'TIPO'
                  Title.Caption = 'Tipo'
                  Width = 79
                  Visible = True
                end
                item
                  Alignment = taCenter
                  Expanded = False
                  FieldName = 'DATAMOVIMENTO'
                  Title.Alignment = taCenter
                  Title.Caption = 'Data do Movimento'
                  Width = 148
                  Visible = True
                end
                item
                  Alignment = taCenter
                  Expanded = False
                  FieldName = 'VALORMOVIMENTO'
                  Title.Alignment = taCenter
                  Title.Caption = 'Valor'
                  Width = 81
                  Visible = True
                end
                item
                  Expanded = False
                  FieldName = 'OBSERVACAO'
                  Title.Caption = 'Observa'#231#227'o'
                  Width = 406
                  Visible = True
                end>
            end
            object edtPesquisa: TEdit
              Left = 6
              Top = 6
              Width = 840
              Height = 28
              Margins.Left = 4
              Margins.Top = 4
              Margins.Right = 4
              Margins.Bottom = 4
              Align = alTop
              TabOrder = 1
            end
          end
        end
      end
      object pnlButtons: TPanel
        Left = 6
        Top = 302
        Width = 860
        Height = 40
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        Align = alBottom
        BevelOuter = bvNone
        Color = 13275746
        Padding.Left = 6
        Padding.Top = 6
        Padding.Right = 6
        Padding.Bottom = 6
        ParentBackground = False
        TabOrder = 1
        object pnlCadastrar: TPanel
          Left = 539
          Top = 6
          Width = 105
          Height = 28
          Margins.Left = 4
          Margins.Top = 4
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alRight
          BevelOuter = bvNone
          Padding.Right = 6
          TabOrder = 0
          object ShpCadastrar: TShape
            Left = 0
            Top = 0
            Width = 99
            Height = 28
            Margins.Left = 4
            Margins.Top = 4
            Margins.Right = 4
            Margins.Bottom = 4
            Align = alClient
            Brush.Color = 8739130
            Pen.Style = psClear
            Shape = stRoundRect
          end
          object btnCadastrar: TSpeedButton
            Left = 0
            Top = 0
            Width = 99
            Height = 28
            Margins.Left = 4
            Margins.Top = 4
            Margins.Right = 4
            Margins.Bottom = 4
            Align = alClient
            Caption = 'Cadastrar'
            Flat = True
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 15649712
            Font.Height = -15
            Font.Name = 'Segoe UI'
            Font.Style = [fsBold]
            ParentFont = False
            OnClick = btnCadastrarClick
          end
        end
        object pnlSalvar: TPanel
          Left = 644
          Top = 6
          Width = 105
          Height = 28
          Margins.Left = 4
          Margins.Top = 4
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alRight
          BevelOuter = bvNone
          Padding.Right = 6
          TabOrder = 1
          object shpSalvar: TShape
            Left = 0
            Top = 0
            Width = 99
            Height = 28
            Margins.Left = 4
            Margins.Top = 4
            Margins.Right = 4
            Margins.Bottom = 4
            Align = alClient
            Brush.Color = 8739130
            Pen.Style = psClear
            Shape = stRoundRect
          end
          object btnSalvar: TSpeedButton
            Left = 0
            Top = 0
            Width = 99
            Height = 28
            Margins.Left = 4
            Margins.Top = 4
            Margins.Right = 4
            Margins.Bottom = 4
            Align = alClient
            Caption = 'Salvar'
            Enabled = False
            Flat = True
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 15649712
            Font.Height = -15
            Font.Name = 'Segoe UI'
            Font.Style = [fsBold]
            ParentFont = False
            OnClick = btnSalvarClick
          end
        end
        object pnlCancelar: TPanel
          Left = 749
          Top = 6
          Width = 105
          Height = 28
          Margins.Left = 4
          Margins.Top = 4
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alRight
          BevelOuter = bvNone
          Padding.Right = 6
          TabOrder = 2
          object ShpCancelar: TShape
            Left = 0
            Top = 0
            Width = 99
            Height = 28
            Margins.Left = 4
            Margins.Top = 4
            Margins.Right = 4
            Margins.Bottom = 4
            Align = alClient
            Brush.Color = 8739130
            Pen.Style = psClear
            Shape = stRoundRect
          end
          object btnCancelar: TSpeedButton
            Left = 0
            Top = 0
            Width = 99
            Height = 28
            Margins.Left = 4
            Margins.Top = 4
            Margins.Right = 4
            Margins.Bottom = 4
            Align = alClient
            Caption = 'Cancelar'
            Enabled = False
            Flat = True
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 15649712
            Font.Height = -15
            Font.Name = 'Segoe UI'
            Font.Style = [fsBold]
            ParentFont = False
            OnClick = btnCancelarClick
          end
        end
      end
    end
  end
  object SQL_Lancamento_Caixa: TFDQuery
    Active = True
    Connection = DM.conexao
    SQL.Strings = (
      'SELECT * FROM CAIXA_LANC')
    Left = 475
    Top = 197
    object SQL_Lancamento_CaixaID: TFDAutoIncField
      FieldName = 'ID'
      Origin = 'ID'
      ProviderFlags = [pfInWhere, pfInKey]
      ReadOnly = True
    end
    object SQL_Lancamento_CaixaDATALANCAMENTO: TDateTimeField
      FieldName = 'DATALANCAMENTO'
      Origin = 'DATALANCAMENTO'
    end
    object SQL_Lancamento_CaixaVALORLANCAMENTO: TFloatField
      FieldName = 'VALORLANCAMENTO'
      Origin = 'VALORLANCAMENTO'
    end
    object SQL_Lancamento_CaixaTIPO: TStringField
      FieldName = 'TIPO'
      Origin = 'TIPO'
      Size = 32767
    end
    object SQL_Lancamento_CaixaOBSERVACAO: TStringField
      FieldName = 'OBSERVACAO'
      Origin = 'OBSERVACAO'
      Size = 80
    end
  end
  object DS_Lancamento_Caixa: TDataSource
    DataSet = SQL_Lancamento_Caixa
    Left = 611
    Top = 197
  end
end
