object Frm_CadastroContasReceber: TFrm_CadastroContasReceber
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'Cadastro de contas a receber'
  ClientHeight = 662
  ClientWidth = 1457
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -15
  Font.Name = 'Segoe UI'
  Font.Style = []
  Position = poScreenCenter
  PixelsPerInch = 120
  TextHeight = 20
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 1457
    Height = 662
    Margins.Left = 4
    Margins.Top = 4
    Margins.Right = 4
    Margins.Bottom = 4
    Align = alClient
    BevelOuter = bvNone
    Color = 8805178
    Padding.Left = 6
    Padding.Top = 6
    Padding.Right = 6
    Padding.Bottom = 6
    ParentBackground = False
    TabOrder = 0
    object Panel8: TPanel
      Left = 6
      Top = 6
      Width = 1445
      Height = 35
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Align = alTop
      Alignment = taLeftJustify
      BevelOuter = bvNone
      BiDiMode = bdLeftToRight
      Caption = '   Cadastro de Documentos a receber'
      Color = 13275746
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 15649712
      Font.Height = -21
      Font.Name = 'Segoe UI'
      Font.Style = [fsBold]
      Padding.Left = 6
      Padding.Top = 6
      Padding.Right = 6
      Padding.Bottom = 6
      ParentBiDiMode = False
      ParentBackground = False
      ParentFont = False
      TabOrder = 0
      object Pnl_sair: TPanel
        Left = 1329
        Top = 6
        Width = 110
        Height = 23
        Cursor = crHandPoint
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        Align = alRight
        BevelOuter = bvNone
        Color = 13274977
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -15
        Font.Name = 'Segoe UI'
        Font.Style = []
        ParentBackground = False
        ParentFont = False
        TabOrder = 0
        object Shape19: TShape
          Left = 0
          Top = 0
          Width = 110
          Height = 23
          Margins.Left = 4
          Margins.Top = 4
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alClient
          Brush.Color = 8739130
          Shape = stRoundRect
        end
        object SpeedButton6: TSpeedButton
          Left = 0
          Top = 0
          Width = 110
          Height = 23
          Cursor = crHandPoint
          Margins.Left = 4
          Margins.Top = 4
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alClient
          Caption = 'Fechar'
          Flat = True
          Font.Charset = DEFAULT_CHARSET
          Font.Color = 15649712
          Font.Height = -16
          Font.Name = 'Segoe UI'
          Font.Style = []
          Font.Quality = fqClearTypeNatural
          ParentFont = False
          OnClick = SpeedButton6Click
        end
      end
    end
    object Panel2: TPanel
      Left = 6
      Top = 41
      Width = 1445
      Height = 615
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Align = alClient
      BevelOuter = bvNone
      Color = 15649712
      Padding.Left = 6
      Padding.Top = 6
      Padding.Right = 6
      Padding.Bottom = 6
      ParentBackground = False
      TabOrder = 1
      object Q: TPageControl
        Left = 6
        Top = 6
        Width = 1433
        Height = 563
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        ActivePage = TabOperacao
        Align = alClient
        TabOrder = 0
        object TabOperacao: TTabSheet
          Margins.Left = 4
          Margins.Top = 4
          Margins.Right = 4
          Margins.Bottom = 4
          Caption = 'Operacao'
          object Panel4: TPanel
            Left = 0
            Top = 0
            Width = 1425
            Height = 528
            Margins.Left = 4
            Margins.Top = 4
            Margins.Right = 4
            Margins.Bottom = 4
            Align = alClient
            BevelOuter = bvNone
            Color = 13274977
            Padding.Left = 6
            Padding.Top = 6
            Padding.Right = 6
            Padding.Bottom = 6
            ParentBackground = False
            TabOrder = 0
            object pnl_dados_user: TPanel
              Left = 6
              Top = 6
              Width = 1413
              Height = 516
              Margins.Left = 4
              Margins.Top = 4
              Margins.Right = 4
              Margins.Bottom = 4
              Align = alClient
              BevelOuter = bvNone
              Color = 15649712
              Padding.Left = 6
              Padding.Top = 6
              Padding.Right = 6
              Padding.Bottom = 6
              ParentBackground = False
              TabOrder = 0
              ExplicitLeft = 0
              ExplicitTop = 8
              object Panel15: TPanel
                Left = 18
                Top = 20
                Width = 73
                Height = 50
                Margins.Left = 4
                Margins.Top = 4
                Margins.Right = 4
                Margins.Bottom = 4
                Align = alCustom
                BevelOuter = bvNone
                Padding.Right = 6
                TabOrder = 0
                object Shape34: TShape
                  Left = 0
                  Top = 0
                  Width = 67
                  Height = 50
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  Align = alClient
                  Brush.Color = 13275746
                  Shape = stRoundRect
                  ExplicitWidth = 68
                end
                object edtID: TDBLabeledEdit
                  Left = 6
                  Top = 25
                  Width = 51
                  Height = 23
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  BiDiMode = bdLeftToRight
                  BorderStyle = bsNone
                  CharCase = ecUpperCase
                  Color = 13275746
                  DataField = 'ID_FORNECEDOR'
                  DataSource = DS_DocumentosaReceber
                  Enabled = False
                  Font.Charset = DEFAULT_CHARSET
                  Font.Color = 16512241
                  Font.Height = -15
                  Font.Name = 'Segoe UI'
                  Font.Style = [fsBold]
                  ParentBiDiMode = False
                  ParentFont = False
                  TabOrder = 0
                  EditLabel.Width = 15
                  EditLabel.Height = 20
                  EditLabel.Margins.Left = 6
                  EditLabel.Margins.Top = 6
                  EditLabel.Margins.Right = 6
                  EditLabel.Margins.Bottom = 6
                  EditLabel.BiDiMode = bdLeftToRight
                  EditLabel.Caption = 'iD'
                  EditLabel.ParentBiDiMode = False
                  EditLabel.Layout = tlCenter
                end
              end
              object Panel5: TPanel
                Left = 93
                Top = 20
                Width = 245
                Height = 50
                Margins.Left = 4
                Margins.Top = 4
                Margins.Right = 4
                Margins.Bottom = 4
                Align = alCustom
                BevelOuter = bvNone
                Padding.Right = 6
                TabOrder = 1
                object Shape1: TShape
                  Left = 0
                  Top = 0
                  Width = 239
                  Height = 50
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  Align = alClient
                  Brush.Color = 13275746
                  Shape = stRoundRect
                end
                object edtNome: TDBLabeledEdit
                  Left = 8
                  Top = 25
                  Width = 220
                  Height = 23
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  BorderStyle = bsNone
                  CharCase = ecUpperCase
                  Color = 13275746
                  DataField = 'NOME_FORNECEDOR'
                  DataSource = DS_DocumentosaReceber
                  Enabled = False
                  Font.Charset = DEFAULT_CHARSET
                  Font.Color = 16512241
                  Font.Height = -15
                  Font.Name = 'Segoe UI'
                  Font.Style = [fsBold]
                  ParentFont = False
                  TabOrder = 0
                  EditLabel.Width = 91
                  EditLabel.Height = 20
                  EditLabel.Margins.Left = 6
                  EditLabel.Margins.Top = 6
                  EditLabel.Margins.Right = 6
                  EditLabel.Margins.Bottom = 6
                  EditLabel.Caption = 'Nome Cliente'
                  EditLabel.Color = clWhite
                  EditLabel.Font.Charset = DEFAULT_CHARSET
                  EditLabel.Font.Color = 15649712
                  EditLabel.Font.Height = -15
                  EditLabel.Font.Name = 'Segoe UI'
                  EditLabel.Font.Style = []
                  EditLabel.ParentColor = False
                  EditLabel.ParentFont = False
                  EditLabel.Layout = tlCenter
                end
              end
              object Panel6: TPanel
                Left = 395
                Top = 20
                Width = 226
                Height = 50
                Margins.Left = 4
                Margins.Top = 4
                Margins.Right = 4
                Margins.Bottom = 4
                Align = alCustom
                BevelOuter = bvNone
                Padding.Right = 6
                TabOrder = 2
                object Shape2: TShape
                  Left = 0
                  Top = 0
                  Width = 220
                  Height = 50
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  Align = alClient
                  Brush.Color = 13275746
                  Shape = stRoundRect
                  ExplicitLeft = 30
                  ExplicitWidth = 166
                end
                object edtSenha: TDBLabeledEdit
                  Left = 8
                  Top = 25
                  Width = 147
                  Height = 23
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  BorderStyle = bsNone
                  CharCase = ecUpperCase
                  Color = 13275746
                  DataField = 'TIPO_DOC'
                  DataSource = DS_DocumentosaReceber
                  Font.Charset = DEFAULT_CHARSET
                  Font.Color = 16512241
                  Font.Height = -15
                  Font.Name = 'Segoe UI'
                  Font.Style = [fsBold]
                  ParentFont = False
                  TabOrder = 0
                  EditLabel.Width = 137
                  EditLabel.Height = 20
                  EditLabel.Margins.Left = 6
                  EditLabel.Margins.Top = 6
                  EditLabel.Margins.Right = 6
                  EditLabel.Margins.Bottom = 6
                  EditLabel.Caption = 'Tipo do documento'
                  EditLabel.Color = clWhite
                  EditLabel.Font.Charset = DEFAULT_CHARSET
                  EditLabel.Font.Color = 15649712
                  EditLabel.Font.Height = -15
                  EditLabel.Font.Name = 'Segoe UI'
                  EditLabel.Font.Style = [fsBold]
                  EditLabel.ParentColor = False
                  EditLabel.ParentFont = False
                  EditLabel.Layout = tlCenter
                end
              end
              object Panel9: TPanel
                Left = 340
                Top = 20
                Width = 48
                Height = 50
                Margins.Left = 4
                Margins.Top = 4
                Margins.Right = 4
                Margins.Bottom = 4
                BevelOuter = bvNone
                Padding.Right = 6
                TabOrder = 3
                object Shape4: TShape
                  Left = 0
                  Top = 0
                  Width = 42
                  Height = 50
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  Align = alClient
                  Brush.Color = 8739130
                  Pen.Style = psClear
                  Shape = stRoundRect
                  ExplicitWidth = 99
                  ExplicitHeight = 28
                end
                object btnPesquisaCliente: TSpeedButton
                  Left = 0
                  Top = 0
                  Width = 42
                  Height = 50
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  Align = alClient
                  Caption = #59169
                  Flat = True
                  Font.Charset = DEFAULT_CHARSET
                  Font.Color = clWhite
                  Font.Height = -15
                  Font.Name = 'Segoe MDL2 Assets'
                  Font.Style = [fsBold]
                  ParentFont = False
                  OnClick = btnPesquisaClienteClick
                  ExplicitWidth = 51
                  ExplicitHeight = 41
                end
              end
              object Panel7: TPanel
                Left = 623
                Top = 20
                Width = 172
                Height = 50
                Margins.Left = 4
                Margins.Top = 4
                Margins.Right = 4
                Margins.Bottom = 4
                Align = alCustom
                BevelOuter = bvNone
                Padding.Right = 6
                TabOrder = 4
                object Shape3: TShape
                  Left = 0
                  Top = 0
                  Width = 166
                  Height = 50
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  Align = alClient
                  Brush.Color = 13275746
                  Shape = stRoundRect
                  ExplicitLeft = 30
                end
                object DBLabeledEdit1: TDBLabeledEdit
                  Left = 8
                  Top = 25
                  Width = 147
                  Height = 23
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  BorderStyle = bsNone
                  CharCase = ecUpperCase
                  Color = 13275746
                  DataField = 'IDENTIFICACAO'
                  DataSource = DS_DocumentosaReceber
                  Font.Charset = DEFAULT_CHARSET
                  Font.Color = 16512241
                  Font.Height = -15
                  Font.Name = 'Segoe UI'
                  Font.Style = [fsBold]
                  ParentFont = False
                  TabOrder = 0
                  EditLabel.Width = 142
                  EditLabel.Height = 20
                  EditLabel.Margins.Left = 6
                  EditLabel.Margins.Top = 6
                  EditLabel.Margins.Right = 6
                  EditLabel.Margins.Bottom = 6
                  EditLabel.Caption = 'Codigo identificador'
                  EditLabel.Color = clWhite
                  EditLabel.Font.Charset = DEFAULT_CHARSET
                  EditLabel.Font.Color = 15649712
                  EditLabel.Font.Height = -15
                  EditLabel.Font.Name = 'Segoe UI'
                  EditLabel.Font.Style = [fsBold]
                  EditLabel.ParentColor = False
                  EditLabel.ParentFont = False
                  EditLabel.Layout = tlCenter
                end
              end
              object Panel10: TPanel
                Left = 797
                Top = 20
                Width = 172
                Height = 50
                Margins.Left = 4
                Margins.Top = 4
                Margins.Right = 4
                Margins.Bottom = 4
                Align = alCustom
                BevelOuter = bvNone
                Padding.Right = 6
                TabOrder = 5
                object Shape5: TShape
                  Left = 0
                  Top = 0
                  Width = 166
                  Height = 50
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  Align = alClient
                  Brush.Color = 13275746
                  Shape = stRoundRect
                  ExplicitLeft = 30
                end
                object DBLabeledEdit2: TDBLabeledEdit
                  Left = 8
                  Top = 25
                  Width = 147
                  Height = 23
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  BorderStyle = bsNone
                  CharCase = ecUpperCase
                  Color = 13275746
                  DataField = 'EMISSAO'
                  DataSource = DS_DocumentosaReceber
                  Font.Charset = DEFAULT_CHARSET
                  Font.Color = 16512241
                  Font.Height = -15
                  Font.Name = 'Segoe UI'
                  Font.Style = [fsBold]
                  ParentFont = False
                  TabOrder = 0
                  EditLabel.Width = 115
                  EditLabel.Height = 20
                  EditLabel.Margins.Left = 6
                  EditLabel.Margins.Top = 6
                  EditLabel.Margins.Right = 6
                  EditLabel.Margins.Bottom = 6
                  EditLabel.Caption = 'Data de emiss'#227'o'
                  EditLabel.Color = clWhite
                  EditLabel.Font.Charset = DEFAULT_CHARSET
                  EditLabel.Font.Color = 15649712
                  EditLabel.Font.Height = -15
                  EditLabel.Font.Name = 'Segoe UI'
                  EditLabel.Font.Style = [fsBold]
                  EditLabel.ParentColor = False
                  EditLabel.ParentFont = False
                  EditLabel.Layout = tlCenter
                end
              end
              object Panel11: TPanel
                Left = 971
                Top = 20
                Width = 172
                Height = 50
                Margins.Left = 4
                Margins.Top = 4
                Margins.Right = 4
                Margins.Bottom = 4
                Align = alCustom
                BevelOuter = bvNone
                Padding.Right = 6
                TabOrder = 6
                object Shape6: TShape
                  Left = 0
                  Top = 0
                  Width = 166
                  Height = 50
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  Align = alClient
                  Brush.Color = 13275746
                  Shape = stRoundRect
                  ExplicitLeft = 30
                end
                object DBLabeledEdit3: TDBLabeledEdit
                  Left = 8
                  Top = 25
                  Width = 147
                  Height = 23
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  BorderStyle = bsNone
                  CharCase = ecUpperCase
                  Color = 13275746
                  DataField = 'VENCIMENTO'
                  DataSource = DS_DocumentosaReceber
                  Font.Charset = DEFAULT_CHARSET
                  Font.Color = 16512241
                  Font.Height = -15
                  Font.Name = 'Segoe UI'
                  Font.Style = [fsBold]
                  ParentFont = False
                  TabOrder = 0
                  EditLabel.Width = 140
                  EditLabel.Height = 20
                  EditLabel.Margins.Left = 6
                  EditLabel.Margins.Top = 6
                  EditLabel.Margins.Right = 6
                  EditLabel.Margins.Bottom = 6
                  EditLabel.Caption = 'Data de vencimento'
                  EditLabel.Color = clWhite
                  EditLabel.Font.Charset = DEFAULT_CHARSET
                  EditLabel.Font.Color = 15649712
                  EditLabel.Font.Height = -15
                  EditLabel.Font.Name = 'Segoe UI'
                  EditLabel.Font.Style = [fsBold]
                  EditLabel.ParentColor = False
                  EditLabel.ParentFont = False
                  EditLabel.Layout = tlCenter
                end
              end
              object Panel12: TPanel
                Left = 22
                Top = 78
                Width = 172
                Height = 50
                Margins.Left = 4
                Margins.Top = 4
                Margins.Right = 4
                Margins.Bottom = 4
                Align = alCustom
                BevelOuter = bvNone
                Padding.Right = 6
                TabOrder = 7
                object Shape7: TShape
                  Left = 0
                  Top = 0
                  Width = 166
                  Height = 50
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  Align = alClient
                  Brush.Color = 13275746
                  Shape = stRoundRect
                  ExplicitLeft = 30
                end
                object DBLabeledEdit4: TDBLabeledEdit
                  Left = 10
                  Top = 25
                  Width = 147
                  Height = 23
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  BorderStyle = bsNone
                  CharCase = ecUpperCase
                  Color = 13275746
                  DataField = 'VALOR'
                  DataSource = DS_DocumentosaReceber
                  Font.Charset = DEFAULT_CHARSET
                  Font.Color = 16512241
                  Font.Height = -15
                  Font.Name = 'Segoe UI'
                  Font.Style = [fsBold]
                  ParentFont = False
                  TabOrder = 0
                  OnKeyPress = DBLabeledEdit4KeyPress
                  EditLabel.Width = 36
                  EditLabel.Height = 20
                  EditLabel.Margins.Left = 6
                  EditLabel.Margins.Top = 6
                  EditLabel.Margins.Right = 6
                  EditLabel.Margins.Bottom = 6
                  EditLabel.Caption = 'Valor'
                  EditLabel.Color = clWhite
                  EditLabel.Font.Charset = DEFAULT_CHARSET
                  EditLabel.Font.Color = 15649712
                  EditLabel.Font.Height = -15
                  EditLabel.Font.Name = 'Segoe UI'
                  EditLabel.Font.Style = [fsBold]
                  EditLabel.ParentColor = False
                  EditLabel.ParentFont = False
                  EditLabel.Layout = tlCenter
                end
              end
              object Panel13: TPanel
                Left = 196
                Top = 78
                Width = 197
                Height = 50
                Margins.Left = 4
                Margins.Top = 4
                Margins.Right = 4
                Margins.Bottom = 4
                Align = alCustom
                BevelOuter = bvNone
                Padding.Right = 6
                TabOrder = 8
                object Shape8: TShape
                  Left = 0
                  Top = 0
                  Width = 191
                  Height = 50
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  Align = alClient
                  Brush.Color = 13275746
                  Shape = stRoundRect
                  ExplicitLeft = 30
                  ExplicitWidth = 166
                end
                object DBLabeledEdit5: TDBLabeledEdit
                  Left = 8
                  Top = 25
                  Width = 147
                  Height = 23
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  BorderStyle = bsNone
                  CharCase = ecUpperCase
                  Color = 13275746
                  DataField = 'QTD_PARCELAS'
                  DataSource = DS_DocumentosaReceber
                  Font.Charset = DEFAULT_CHARSET
                  Font.Color = 16512241
                  Font.Height = -15
                  Font.Name = 'Segoe UI'
                  Font.Style = [fsBold]
                  ParentFont = False
                  TabOrder = 0
                  EditLabel.Width = 163
                  EditLabel.Height = 20
                  EditLabel.Margins.Left = 6
                  EditLabel.Margins.Top = 6
                  EditLabel.Margins.Right = 6
                  EditLabel.Margins.Bottom = 6
                  EditLabel.Caption = 'Quantidade de parcelas'
                  EditLabel.Color = clWhite
                  EditLabel.Font.Charset = DEFAULT_CHARSET
                  EditLabel.Font.Color = 15649712
                  EditLabel.Font.Height = -15
                  EditLabel.Font.Name = 'Segoe UI'
                  EditLabel.Font.Style = [fsBold]
                  EditLabel.ParentColor = False
                  EditLabel.ParentFont = False
                  EditLabel.Layout = tlCenter
                end
              end
              object Panel14: TPanel
                Left = 395
                Top = 78
                Width = 172
                Height = 50
                Margins.Left = 4
                Margins.Top = 4
                Margins.Right = 4
                Margins.Bottom = 4
                Align = alCustom
                BevelOuter = bvNone
                Padding.Right = 6
                TabOrder = 9
                object Shape9: TShape
                  Left = 0
                  Top = 0
                  Width = 166
                  Height = 50
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  Align = alClient
                  Brush.Color = 13275746
                  Shape = stRoundRect
                  ExplicitLeft = 30
                end
                object DBLabeledEdit6: TDBLabeledEdit
                  Left = 6
                  Top = 25
                  Width = 147
                  Height = 23
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  BorderStyle = bsNone
                  CharCase = ecUpperCase
                  Color = 13275746
                  DataField = 'DESCONTO'
                  DataSource = DS_DocumentosaReceber
                  Font.Charset = DEFAULT_CHARSET
                  Font.Color = 16512241
                  Font.Height = -15
                  Font.Name = 'Segoe UI'
                  Font.Style = [fsBold]
                  ParentFont = False
                  TabOrder = 0
                  EditLabel.Width = 66
                  EditLabel.Height = 20
                  EditLabel.Margins.Left = 6
                  EditLabel.Margins.Top = 6
                  EditLabel.Margins.Right = 6
                  EditLabel.Margins.Bottom = 6
                  EditLabel.Caption = 'Desconto'
                  EditLabel.Color = clWhite
                  EditLabel.Font.Charset = DEFAULT_CHARSET
                  EditLabel.Font.Color = 15649712
                  EditLabel.Font.Height = -15
                  EditLabel.Font.Name = 'Segoe UI'
                  EditLabel.Font.Style = [fsBold]
                  EditLabel.ParentColor = False
                  EditLabel.ParentFont = False
                  EditLabel.Layout = tlCenter
                end
              end
              object Panel16: TPanel
                Left = 18
                Top = 136
                Width = 553
                Height = 185
                Margins.Left = 4
                Margins.Top = 4
                Margins.Right = 4
                Margins.Bottom = 4
                Align = alCustom
                BevelOuter = bvNone
                Padding.Right = 6
                TabOrder = 10
                object Shape10: TShape
                  Left = 0
                  Top = 0
                  Width = 547
                  Height = 185
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  Align = alClient
                  Brush.Color = 13275746
                  Shape = stRoundRect
                  ExplicitLeft = 30
                  ExplicitWidth = 166
                  ExplicitHeight = 50
                end
                object DBLabeledEdit7: TDBLabeledEdit
                  Left = 14
                  Top = 30
                  Width = 517
                  Height = 131
                  Margins.Left = 4
                  Margins.Top = 4
                  Margins.Right = 4
                  Margins.Bottom = 4
                  BorderStyle = bsNone
                  CharCase = ecUpperCase
                  Color = 13275746
                  DataField = 'OBSERVACAO'
                  DataSource = DS_DocumentosaReceber
                  Font.Charset = DEFAULT_CHARSET
                  Font.Color = 16512241
                  Font.Height = -15
                  Font.Name = 'Segoe UI'
                  Font.Style = [fsBold]
                  ParentFont = False
                  TabOrder = 0
                  EditLabel.Width = 82
                  EditLabel.Height = 20
                  EditLabel.Margins.Left = 6
                  EditLabel.Margins.Top = 6
                  EditLabel.Margins.Right = 6
                  EditLabel.Margins.Bottom = 6
                  EditLabel.Caption = 'Observa'#231#227'o'
                  EditLabel.Color = clWhite
                  EditLabel.Font.Charset = DEFAULT_CHARSET
                  EditLabel.Font.Color = 15649712
                  EditLabel.Font.Height = -15
                  EditLabel.Font.Name = 'Segoe UI'
                  EditLabel.Font.Style = [fsBold]
                  EditLabel.ParentColor = False
                  EditLabel.ParentFont = False
                  EditLabel.Layout = tlCenter
                end
              end
            end
          end
        end
        object TabPesquisa: TTabSheet
          Margins.Left = 4
          Margins.Top = 4
          Margins.Right = 4
          Margins.Bottom = 4
          Caption = 'Pesquisa'
          ImageIndex = 1
          object Panel3: TPanel
            Left = 0
            Top = 0
            Width = 1425
            Height = 528
            Margins.Left = 4
            Margins.Top = 4
            Margins.Right = 4
            Margins.Bottom = 4
            Align = alClient
            Color = 14079702
            Padding.Left = 5
            Padding.Top = 5
            Padding.Right = 5
            Padding.Bottom = 5
            ParentBackground = False
            TabOrder = 0
            object gridDocumentos: TDBGrid
              Left = 6
              Top = 34
              Width = 1413
              Height = 488
              Hint = 'Clique duas vezes para selecionar'
              Margins.Left = 4
              Margins.Top = 4
              Margins.Right = 4
              Margins.Bottom = 4
              Align = alClient
              BorderStyle = bsNone
              DataSource = DS_DocumentosaReceber
              DrawingStyle = gdsClassic
              FixedColor = 14079702
              GradientStartColor = clCream
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -15
              Font.Name = 'Segoe UI'
              Font.Style = []
              ParentFont = False
              ParentShowHint = False
              ReadOnly = True
              ShowHint = True
              TabOrder = 0
              TitleFont.Charset = DEFAULT_CHARSET
              TitleFont.Color = clWindowText
              TitleFont.Height = -15
              TitleFont.Name = 'Segoe UI'
              TitleFont.Style = [fsBold]
              OnDblClick = gridDocumentosDblClick
              Columns = <
                item
                  Expanded = False
                  FieldName = 'NOME_FORNECEDOR'
                  Width = 742
                  Visible = True
                end
                item
                  Expanded = False
                  FieldName = 'IDENTIFICACAO'
                  Width = 140
                  Visible = True
                end
                item
                  Expanded = False
                  FieldName = 'EMISSAO'
                  Width = 200
                  Visible = True
                end
                item
                  Expanded = False
                  FieldName = 'VENCIMENTO'
                  Width = 200
                  Visible = True
                end
                item
                  Alignment = taLeftJustify
                  Expanded = False
                  FieldName = 'VALOR'
                  Visible = True
                end>
            end
            object edtPesquisa: TEdit
              Left = 6
              Top = 6
              Width = 1413
              Height = 28
              Margins.Left = 4
              Margins.Top = 4
              Margins.Right = 4
              Margins.Bottom = 4
              Align = alTop
              TabOrder = 1
            end
          end
        end
      end
      object pnlButtons: TPanel
        Left = 6
        Top = 569
        Width = 1433
        Height = 40
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        Align = alBottom
        BevelOuter = bvNone
        Color = 13275746
        Padding.Left = 6
        Padding.Top = 6
        Padding.Right = 6
        Padding.Bottom = 6
        ParentBackground = False
        TabOrder = 1
        object pnlEditar: TPanel
          Left = 1007
          Top = 6
          Width = 105
          Height = 28
          Margins.Left = 4
          Margins.Top = 4
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alRight
          BevelOuter = bvNone
          Padding.Right = 6
          TabOrder = 0
          object Shpeditar: TShape
            Left = 0
            Top = 0
            Width = 99
            Height = 28
            Margins.Left = 4
            Margins.Top = 4
            Margins.Right = 4
            Margins.Bottom = 4
            Align = alClient
            Brush.Color = 8739130
            Pen.Style = psClear
            Shape = stRoundRect
          end
          object btnEditar: TSpeedButton
            Left = 0
            Top = 0
            Width = 99
            Height = 28
            Margins.Left = 4
            Margins.Top = 4
            Margins.Right = 4
            Margins.Bottom = 4
            Align = alClient
            Caption = 'Editar'
            Flat = True
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 15649712
            Font.Height = -15
            Font.Name = 'Segoe UI'
            Font.Style = [fsBold]
            ParentFont = False
            OnClick = btnEditarClick
          end
        end
        object pnlCadastrar: TPanel
          Left = 902
          Top = 6
          Width = 105
          Height = 28
          Margins.Left = 4
          Margins.Top = 4
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alRight
          BevelOuter = bvNone
          Padding.Right = 6
          TabOrder = 1
          object ShpCadastrar: TShape
            Left = 0
            Top = 0
            Width = 99
            Height = 28
            Margins.Left = 4
            Margins.Top = 4
            Margins.Right = 4
            Margins.Bottom = 4
            Align = alClient
            Brush.Color = 8739130
            Pen.Style = psClear
            Shape = stRoundRect
          end
          object btnCadastrar: TSpeedButton
            Left = 0
            Top = 0
            Width = 99
            Height = 28
            Margins.Left = 4
            Margins.Top = 4
            Margins.Right = 4
            Margins.Bottom = 4
            Align = alClient
            Caption = 'Cadastrar'
            Flat = True
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 15649712
            Font.Height = -15
            Font.Name = 'Segoe UI'
            Font.Style = [fsBold]
            ParentFont = False
            OnClick = btnCadastrarClick
            ExplicitLeft = -2
            ExplicitTop = -2
          end
        end
        object pnlSalvar: TPanel
          Left = 1112
          Top = 6
          Width = 105
          Height = 28
          Margins.Left = 4
          Margins.Top = 4
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alRight
          BevelOuter = bvNone
          Padding.Right = 6
          TabOrder = 2
          object shpSalvar: TShape
            Left = 0
            Top = 0
            Width = 99
            Height = 28
            Margins.Left = 4
            Margins.Top = 4
            Margins.Right = 4
            Margins.Bottom = 4
            Align = alClient
            Brush.Color = 8739130
            Pen.Style = psClear
            Shape = stRoundRect
          end
          object btnSalvar: TSpeedButton
            Left = 0
            Top = 0
            Width = 99
            Height = 28
            Margins.Left = 4
            Margins.Top = 4
            Margins.Right = 4
            Margins.Bottom = 4
            Align = alClient
            Caption = 'Salvar'
            Enabled = False
            Flat = True
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 15649712
            Font.Height = -15
            Font.Name = 'Segoe UI'
            Font.Style = [fsBold]
            ParentFont = False
            OnClick = btnSalvarClick
          end
        end
        object pnlCancelar: TPanel
          Left = 1217
          Top = 6
          Width = 105
          Height = 28
          Margins.Left = 4
          Margins.Top = 4
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alRight
          BevelOuter = bvNone
          Padding.Right = 6
          TabOrder = 3
          object ShpCancelar: TShape
            Left = 0
            Top = 0
            Width = 99
            Height = 28
            Margins.Left = 4
            Margins.Top = 4
            Margins.Right = 4
            Margins.Bottom = 4
            Align = alClient
            Brush.Color = 8739130
            Pen.Style = psClear
            Shape = stRoundRect
          end
          object btnCancelar: TSpeedButton
            Left = 0
            Top = 0
            Width = 99
            Height = 28
            Margins.Left = 4
            Margins.Top = 4
            Margins.Right = 4
            Margins.Bottom = 4
            Align = alClient
            Caption = 'Cancelar'
            Enabled = False
            Flat = True
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 15649712
            Font.Height = -15
            Font.Name = 'Segoe UI'
            Font.Style = [fsBold]
            ParentFont = False
            OnClick = btnCancelarClick
          end
        end
        object pnlExcluir: TPanel
          Left = 1322
          Top = 6
          Width = 105
          Height = 28
          Margins.Left = 4
          Margins.Top = 4
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alRight
          BevelOuter = bvNone
          Padding.Right = 6
          TabOrder = 4
          object shpExcluir: TShape
            Left = 0
            Top = 0
            Width = 99
            Height = 28
            Margins.Left = 4
            Margins.Top = 4
            Margins.Right = 4
            Margins.Bottom = 4
            Align = alClient
            Brush.Color = 8739130
            Pen.Style = psClear
            Shape = stRoundRect
          end
          object btnExcluir: TSpeedButton
            Left = 0
            Top = 0
            Width = 99
            Height = 28
            Margins.Left = 4
            Margins.Top = 4
            Margins.Right = 4
            Margins.Bottom = 4
            Align = alClient
            Caption = 'Excluir'
            Flat = True
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 15649712
            Font.Height = -15
            Font.Name = 'Segoe UI'
            Font.Style = [fsBold]
            ParentFont = False
            OnClick = btnExcluirClick
          end
        end
      end
    end
  end
  object SQL_DocumentosaReceber: TFDQuery
    Active = True
    Connection = DM.conexao
    SQL.Strings = (
      'select * from DOC_RECEBER')
    Left = 583
    Top = 395
  end
  object DS_DocumentosaReceber: TDataSource
    DataSet = SQL_DocumentosaReceber
    Left = 792
    Top = 390
  end
end
